name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      # Step 2: SonarCloud Scan
      # - name: SonarQube Cloud Scan
      #   uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.organization=ishandilmith
      #       -Dsonar.projectKey=IshanDilmith_order-microservice

      # Step 3: Login to Azure Container Registry
      - name: Login to ACR
        env:
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: echo "$ACR_PASSWORD" | docker login "$ACR_LOGIN_SERVER" -u "$ACR_USERNAME" --password-stdin

      # Step 4: Build and Push Cart Service Image
      - name: Build Cart Service Image
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: docker build -t "$ACR_LOGIN_SERVER"/cart-service:${{ github.run_number }} .

      # Step 5: Push Cart Service Image
      - name: Push Cart Service Image
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: docker push "$ACR_LOGIN_SERVER"/cart-service:${{ github.run_number }}